version: '2'
services:
  hubot:
    build: .
    environment:
      - HUBOT_SLACK_TOKEN
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/hubot
    depends_on:
      - redis
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
     - ./redis:/data
