FROM node:latest

MAINTAINER Jonty Bale

ENV HUBOT_PORT 8080
ENV HUBOT_ADAPTER slack
ENV HUBOT_NAME hubot
ENV PORT ${HUBOT_PORT}
ENV HUBOT_SLACK_BOTNAME ${HUBOT_NAME}

ENV BOTDIR /opt/${HUBOT_NAME}

ENV REDIS_URL=redis://redis:6379

# setup to install and then run
WORKDIR ${BOTDIR}

EXPOSE ${HUBOT_PORT}

CMD bin/hubot

