FROM node:latest

MAINTAINER Jonty Bale

ENV BOTDIR /opt/hubot
ENV HUBOT_PORT 8080
ENV HUBOT_ADAPTER slack
ENV HUBOT_NAME hubot
ENV HUBOT_SLACK_TOKEN xoxb-64451284119-MOFC9IzVRC36jqI5lpdLzVNB
ENV HUBOT_SLACK_BOTNAME ${HUBOT_NAME}
ENV PORT ${HUBOT_PORT}

ENV REDIS_URL=redis://redis:6379

# setup to install and then run
WORKDIR ${BOTDIR}

EXPOSE ${HUBOT_PORT}

CMD bin/hubot

